"""Add institution_name to PlaidItem

Revision ID: 134bbdf14d99
Revises: 517d7159b8d7
Create Date: 2024-12-29 18:29:30.142552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134bbdf14d99'
down_revision = '517d7159b8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('institution_name')

    # ### end Alembic commands ###
