"""add cursor to PlaidItem

Revision ID: 1eccdd5b83b3
Revises: efa658a152eb
Create Date: 2024-12-26 22:11:18.701872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eccdd5b83b3'
down_revision = 'efa658a152eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cursor', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('cursor')

    # ### end Alembic commands ###
