"""secure PlaidItem clumns

Revision ID: 20daec978fd3
Revises: 50cfef26d876
Create Date: 2025-03-10 14:14:30.202975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20daec978fd3'
down_revision = '50cfef26d876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###
