"""Fixed PlaidItem model

Revision ID: 2257e57642c2
Revises: 9ef62b5e1b14
Create Date: 2025-02-28 14:23:29.217238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2257e57642c2'
down_revision = '9ef62b5e1b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.String(length=255), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
