"""Add institution_id to PlaidItem

Revision ID: 2ad632c01777
Revises: 7ec974948e0f
Create Date: 2024-12-29 18:15:40.382306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad632c01777'
down_revision = '7ec974948e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('institution_id')

    # ### end Alembic commands ###
