"""add tags to admin logging

Revision ID: 2b72c209fab9
Revises: 461407f67f2b
Create Date: 2025-07-26 13:22:18.557551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b72c209fab9'
down_revision = '461407f67f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_categorization_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_tags_guess', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('user_tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tags_accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_categorization_log', schema=None) as batch_op:
        batch_op.drop_column('tags_accepted')
        batch_op.drop_column('user_tags')
        batch_op.drop_column('ai_tags_guess')

    # ### end Alembic commands ###
