"""remove unique constraint

Revision ID: 468a2dec8ef1
Revises: ad48a1ce46bf
Create Date: 2025-01-01 11:17:37.999306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468a2dec8ef1'
down_revision = 'ad48a1ce46bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('uq_transaction_transaction_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_transaction_transaction_id', ['transaction_id'])

    # ### end Alembic commands ###
