"""fix institution column

Revision ID: 517d7159b8d7
Revises: 2ad632c01777
Create Date: 2024-12-29 18:28:09.231288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517d7159b8d7'
down_revision = '2ad632c01777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.String(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('institution_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('institution_id')

    # ### end Alembic commands ###
