"""Add many-to-many relationship for tags

Revision ID: 5e3861ebef6f
Revises: 468a2dec8ef1
Create Date: 2025-01-02 16:30:23.271553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3861ebef6f'
down_revision = '468a2dec8ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.VARCHAR(length=50), server_default=sa.text("'None'"), nullable=False))

    # ### end Alembic commands ###
