"""readd tags stuff

Revision ID: 65dee00451a9
Revises: df70c2be1bd7
Create Date: 2025-01-02 21:15:49.591145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65dee00451a9'
down_revision = 'df70c2be1bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.VARCHAR(length=50), server_default=sa.text("'None'"), nullable=False))

    # ### end Alembic commands ###
