"""change tag column name in transactions

Revision ID: 95179a0397ee
Revises: 134bbdf14d99
Create Date: 2024-12-30 15:14:01.912945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95179a0397ee'
down_revision = '134bbdf14d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=50), server_default='None', nullable=False))
        batch_op.drop_column('tag_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_name', sa.VARCHAR(length=50), server_default=sa.text("'None'"), nullable=False))
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
