"""empty message

Revision ID: 95716aa7377f
Revises: 4b6d3a01448e
Create Date: 2024-07-29 09:44:41.990205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95716aa7377f'
down_revision = '4b6d3a01448e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_tags_color_id', 'tag_color', ['color_id'], ['id'])
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tags_color_id', type_='foreignkey')

    op.create_table('_alembic_tmp_tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('color_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['tag_color.id'], name='fk_tags_color_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_tags_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
