"""remove total_amount column from Money table

Revision ID: 9c342ad743cf
Revises: aa67ec1c456c
Create Date: 2025-01-09 20:01:13.697917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c342ad743cf'
down_revision = 'aa67ec1c456c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###
