"""add access_token_encrypted colmun

Revision ID: 9ed97fffbd6c
Revises: 20daec978fd3
Create Date: 2025-03-10 14:23:29.044246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed97fffbd6c'
down_revision = '20daec978fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token_encrypted', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('access_token_encrypted')

    # ### end Alembic commands ###
