"""reupdate plaid table

Revision ID: 9ef62b5e1b14
Revises: 9acf437950dd
Create Date: 2025-02-28 14:19:23.030677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef62b5e1b14'
down_revision = '9acf437950dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###
