"""add total_amount column to Money table

Revision ID: aa67ec1c456c
Revises: 7d00e3df003d
Create Date: 2025-01-09 20:00:24.176232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa67ec1c456c'
down_revision = '7d00e3df003d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
