"""Added encrypted fields for payment_id, transfer_id, and user_token

Revision ID: b51691953fed
Revises: 9c342ad743cf
Create Date: 2025-02-13 14:25:12.413508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51691953fed'
down_revision = '9c342ad743cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
