"""add transaction_id column

Revision ID: e0671064d9e7
Revises: 618dd177afcc
Create Date: 2024-12-31 09:42:45.000397

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = 'e0671064d9e7'
down_revision = '618dd177afcc'
branch_labels = None
depends_on = None

def generate_uuid():
    """Generate a UUID string."""
    return str(uuid.uuid4())

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(), nullable=False, server_default=sa.text(f"'{generate_uuid()}'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
