"""readd timestamp to transactions

Revision ID: e52b9f3c8b26
Revises: e082445cbbcc
Create Date: 2024-12-30 16:41:32.677558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52b9f3c8b26'
down_revision = 'e082445cbbcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('account_id', sa.VARCHAR(), nullable=True),
    sa.Column('pending', sa.BOOLEAN(), nullable=True),
    sa.Column('bank_account', sa.VARCHAR(), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=50), server_default=sa.text("'None'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###
