"""reset for now

Revision ID: e80d77caf795
Revises: 9ed97fffbd6c
Create Date: 2025-03-10 14:25:34.176444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80d77caf795'
down_revision = '9ed97fffbd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.String(length=255), server_default='', nullable=False))
        batch_op.drop_column('access_token_encrypted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token_encrypted', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
